[package]
name = "llm-chain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A library for chaining LLM invocations (such as ChatGPT or LLaMA) in series to complete complex tasks, such as text summarization."
license.workspace = true
keywords = ["llm", "langchain", "chatgpt", "chain"]
categories = ["science"]
authors.workspace = true
readme = "../docs/README.md"
repository.workspace = true

[features]
default = ["serialization"]
serialization = ["dep:serde", "dep:serde_yaml_ng"]
async = ["dep:tokio"]

[dependencies]
futures.workspace = true
serde = { workspace = true, optional = true }
serde_yaml_ng = { workspace = true, optional = true }
thiserror.workspace = true
tokio = { workspace = true, optional = true, features = ["fs", "io-util"] }
trait-variant.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
