[package]
name = "llm-chain-openai"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A library implementing `llm-chains` for OpenAI's models. Chains can be used to apply the model series to complete complex tasks, such as text summarization."
license.workspace = true
keywords = ["llm", "langchain", "openai", "gpt", "chain"]
categories = ["science"]
authors.workspace = true
readme = "../docs/README.md"
repository.workspace = true

[features]
default = ["serialization"]
serialization = ["dep:serde", "llm-chain/serialization"]

[dependencies]
async-openai.workspace = true
llm-chain.workspace = true
reqwest.workspace = true
secrecy.workspace = true
serde = { workspace = true, optional = true }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_yaml_ng.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }

[lints]
workspace = true
