[package]
name = "llm-chain-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A library for providing Large Language Models with tools (also known as 'actions') that they can trigger"
license.workspace = true
keywords = ["llm", "langchain", "agents", "chain"]
categories = ["science"]
authors.workspace = true
readme = "README.md"
repository.workspace = true

[dependencies]
llm-chain.workspace = true
serde.workspace = true
serde_yaml_ng.workspace = true
thiserror.workspace = true

[dev-dependencies]
llm-chain-openai = { path = "../llm-chain-openai" }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }

[lints]
workspace = true
